MiNiFi Config Version: 3
Flow Controller:
  name: CaptureMQTT
  comment: ''
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
  variable registry properties: ''
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
  implementation: org.apache.nifi.provenance.MiNiFiPersistentProvenanceRepository
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors:
- id: b82ef00e-d5fc-36a7-0000-000000000000
  name: Capture Photo and MXClassify
  class: org.apache.nifi.processors.standard.ExecuteProcess
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 60 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Argument Delimiter: ' '
    Batch Duration:
    Command: /media/nvidia/96ed93f9-7c40-4999-85ba-3eb24262d0a5/mxclassify.sh
    Command Arguments:
    Redirect Error Stream: 'false'
    Working Directory:
- id: 4ae114de-c865-3ec0-0000-000000000000
  name: PublishMQTT
  class: org.apache.nifi.processors.mqtt.PublishMQTT
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list:
  - failure
  - success
  Properties:
    Broker URI: tcp://m13.cloudmqtt.com:17769
    Client ID: minifijetson
    Connection Timeout (seconds): '30'
    Keep Alive Interval (seconds): '60'
    Last Will Message:
    Last Will QoS Level:
    Last Will Retain:
    Last Will Topic:
    MQTT Specification Version: '0'
    Password: 5Ox2ZIbLor7z
    Quality of Service(QoS): '1'
    Retain Message: 'false'
    SSL Context Service:
    Session state: 'true'
    Topic: JETSON
    Username: zvrxunpj
Controller Services: []
Process Groups: []
Input Ports: []
Output Ports: []
Funnels: []
Connections:
- id: 58a4d730-d49e-3c8d-0000-000000000000
  name: Capture Photo and MXClassify/success/PublishMQTT
  source id: b82ef00e-d5fc-36a7-0000-000000000000
  source relationship names:
  - success
  destination id: 4ae114de-c865-3ec0-0000-000000000000
  max work queue size: 10000
  max work queue data size: 1 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
Remote Process Groups: []
NiFi Properties Overrides: {}
